### ISSUE TITLE
return value of 'list_of_elements_of_multiplicative_g' for rings of integers modulo n should be a ring element?

### ISSUE THREAD

**Issue by jakobkroeker** [sagemath/sage-archive-2023-02-01#8]
Hello,

the 'list_of_elements_of_multiplicative_group' returns Python integers
instead of ring elements;#

```
R = Integers(15)
l=R.list_of_elements_of_multiplicative_group()
l[5]*l[5]
#121; I would expect 1.
```

 should this be changed?

**Comment by ohanar** [comment]
Probably, the issue is that the return type is not what you would expect.

FYI, this repository is still a work in progress -- sage is moving over to git for development purposes, but we aren't not there yet. Reporting to the mailing list sage-devel@googlegroups.com or getting an account on trac.sagemath.org and making a ticket the appropriate way to report issues.
